---
- hosts: all
  become: true
  pre_tasks:

    - name: install updates
      tags: always
      apt:
        upgrade: dist
        update_cache: yes

- hosts: web_servers
  become: true
  tasks:

    - name: install apache2 and php package
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest

    - name: copy default html file for site
      tags: [apache, apache2, ubuntu]
      copy:
         src: default_site.html
         dest: /var/www/html/index.html
         owner: root
         group: root
         mode: '0644'

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
